development:
  adapter: postgresql
  host: localhost
  database: mydb
  user: pguser
  password: dealadmin
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  host: localhost
  database: mydb_test
  user: pguser
  password: dealadmin
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  host: localhost
  database: mydb
  user: pguser
  password: dealadmin
  pool: 5
  timeout: 5000
